### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by ReconChickenARMA** [OverlordZorn/S.T.O.R.M.-Framework#54]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Read Before you Post !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- Steps to reproduce are crucial. Without reproduction, its just a guessing game.
- Does the Issue seem to be a mod conflict? Try reproduce the problem only with required mods.

#############  Start of Issue #############
**What is wrong**
Arma crashes on startup
**To Reproduce**
Downloaded Steam Workshop version of mod, tried running it with a fairly stable modset, and crashed before full startup

**Expected behavior**
I want the game to launch.

**Error Messages?**

Include file z\storm\addons\based\script_macros.pp not found.

**RPT's**
`=====================================================================
== C:\Program Files (x86)\Steam\steamapps\common\Arma 3\Arma3_x64.exe
== "C:\Program Files (x86)\Steam\steamapps\common\Arma 3\Arma3_x64.exe" "-mod=WS;RF;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CBA_A3;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@ace;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Immersion Cigs;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Zeus Enhanced;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Arma 3 Aegis;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CVO Auxiliary Mod;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Hate's Digital Camera;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@O&T Expansion Eden;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@3den Enhanced;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Deformer;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@GreenMag;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Sonus;C:\Program Files (x86
Original output filename: Arma3Retail_DX11_x64
Exe timestamp: 2024/03/21 14:45:00
Current time:  2024/04/16 22:50:59

Type: Public
Build: Stable
Version: 2.16.151618

Allocator: C:\Program Files (x86)\Steam\steamapps\common\Arma 3\Dll\tbb4malloc_bi_x64.dll [2017.0.0.0] [2017.0.0.0]
PhysMem: 24 GiB, VirtMem : 131072 GiB, AvailPhys : 17 GiB, AvailVirt : 131068 GiB, AvailPage : 17 GiB, PageSize : 4.0 KiB/2.0 MiB/HasLockMemory, CPUCount : 4
=====================================================================

22:50:59 Detected number of DLCs: 22
22:50:59 ---------------------------------------------------------- Game ----------------------------------------------------------
22:50:59                                                                name      appId   owned  installed  available   isDlc
22:50:59                                                              Arma 3     107410     yes        yes        yes      no
22:50:59                                                             Unknown         -1      no         no         no     yes
22:50:59 ---------------------------------------------------------- Dlcs ----------------------------------------------------------
22:50:59  index                                                         name      appId   owned  installed  available   isDlc
22:50:59      0                                                  Arma 3 Maps     249861      no         no         no     yes
22:50:59      1                                        Arma 3 Tactical Guide     249862      no         no         no     yes
22:50:59      2                                                  Arma 3 Zeus     275700     yes        yes        yes     yes
22:50:59      3                                                 Arma 3 Karts     288520     yes        yes        yes     yes
22:50:59      4                                           Arma 3 Helicopters     304380     yes        yes        yes     yes
22:50:59      5                                          Arma 3 DLC Bundle 1     304400      no         no         no     yes
22:50:59      6                                              Arma 3 Marksmen     332350     yes        yes        yes     yes
22:50:59      7                                                  Arma 3 Apex     395180     yes        yes        yes     yes
22:50:59      8                                           Arma 3 Laws of War     571710     yes        yes        yes     yes
22:50:59      9                                                  Arma 3 Jets     601670     yes        yes        yes     yes
22:50:59     10                                          Arma 3 DLC Bundle 2     612480      no         no         no     yes
22:50:59     11                                                Arma 3 Malden     639600     yes        yes        yes     yes
22:50:59     12                                  Arma 3 Tac-Ops Mission Pack     744950     yes        yes        yes     yes
22:50:59     13                                                 Arma 3 Tanks     798390     yes        yes        yes     yes
22:50:59     14                                               Arma 3 Contact    1021790     yes        yes        yes     yes
22:50:59     15   Arma 3 Creator DLC: Global Mobilization - Cold War Germany    1042220     yes        yes        yes     yes
22:50:59     16                           Arma 3 Creator DLC: Spearhead 1944    1175380      no         no        yes     yes
22:50:59     17                      Arma 3 Creator DLC: S.O.G. Prairie Fire    1227700     yes        yes        yes     yes
22:50:59     18                        Arma 3 Creator DLC: CSLA Iron Curtain    1294440      no         no        yes     yes
22:50:59     19                                            Arma 3 Art of War    1325500     yes        yes        yes     yes
22:50:59     20                           Arma 3 Creator DLC: Western Sahara    1681170     yes        yes        yes     yes
22:50:59     21                          Arma 3 Creator DLC: Reaction Forces    2647760     yes        yes        yes     yes
22:50:59 --------------------------------------------------------------------------------------------------------------------------
22:51:00 ErrorMessage: Include file z\storm\addons\based\script_macros.hpp not found.
22:51:00  ➥ Context: Preprocessing file: C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@S.T.O.R.M. Framework - DEV - CLOSED BETA\mod.cpp at 1
22:51:00 Application terminated intentionally
22:51:00  ➥ Context: Preprocessing file: C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@S.T.O.R.M. Framework - DEV - CLOSED BETA\mod.cpp at 1
ErrorMessage: Include file z\storm\addons\based\script_macros.hpp not found.
=======================================================
-------------------------------------------------------
Exception code: 0000DEAD  at 4D27AB89
Version 2.16.151618
Fault time: 2024/04/16 22:52:55
Fault address:  4D27AB89 01:00029B89ll C:\WINDOWS\System32\KERNELBASE.dll
file:     
world:    
Prev. code bytes: BA BF 08 00 48 8D 4C 24 20 48 FF 15 BF A5 1B 00
Fault code bytes: 0F 1F 44 00 00 48 8B 8C 24 C0 00 00 00 48 33 CC
=======================================================
note: Minidump has been generated into the file C:\Users\Wyatt S\AppData\Local\Arma 3\Arma3_x64_2024-04-16_22-50-59.mdmp
`
**Versions:**
S.T.O.R.M.: Closed Beta
Arma3: 2.16.151618
cba: x.x.x
ace: x.x.x

**Additional context**

**Comment by OverlordZorn** [comment]
@ReconChickenARMA please add your rpt via https://gist.github.com/ or https://pastebin.com/

**Comment by OverlordZorn** [comment]
Cannot reproduce - Works fine for me with CBA and Storm DEV version only.

Try repairing CBA and STORM, make sure your CBA is up-to-date, if needed repair your arma 3 game.
