### ISSUE TITLE
[BUG] Crash on Transition Complete

### ISSUE THREAD

**Issue by ReconChickenARMA** [OverlordZorn/S.T.O.R.M.-Framework#60]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Read Before you Post !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- Steps to reproduce are crucial. Without reproduction, its just a guessing game.
- Does the Issue seem to be a mod conflict? Try reproduce the problem only with required mods.

#############  Start of Issue #############
**What is wrong**
Game freezes immediately after the Transition Complete message displays

**To Reproduce**
Started a fresh editor mission
placed a unit
set overcast to >50%
Started mission
Launched Snowstorm preset, 1 minute transition, target value 1
After transition completes, game freezes
Note: Tried on both Stratis and Tanoa, so I don't think it's a map specific issue.

**Expected behavior**
Snowstorm continues running until I initiate the transition again.

**Error Messages?**
0xCFFFFFFF - STATUS_APPLICATION_HANG

**RPT's**
https://pastebin.com/raw/yzadGpCC
```
https://pastebin.com/
https://gist.github.com/
drag&drop the whole file
dont copy the content into the issue.
```
**Versions:**
```
Arma3: 2.16.151618
S.T.O.R.M.: 0.05.0.2.BETA
cba: 3.17.0.24041
```

**Additional context**
Edit: Tried with the Sandstorm, crashed in the same way.
https://pastebin.com/enaAnU7i

**Comment by OverlordZorn** [comment]
le Funny: When i built the mod with hemtt and test launch it, i cannot reproduce the issue :]

**Comment by OverlordZorn** [comment]
![wtf-what-the-fuck](https://github.com/OverlordZorn/S.T.O.R.M.-Framework/assets/56258612/c742d79d-5988-43e0-90b8-657cab55aea3)

**Comment by jupster** [comment]
Might be worth running the game in debug not just the mod (not sure if you can force that but would be a good thing to do while in dev.) cause might be able to find about a bit more info on why it is happening to @ReconChickenARMA

**Comment by OverlordZorn** [comment]
i was able to reproduce it with the version from the workshop

**Comment by OverlordZorn** [comment]
i *might* have identified the issue

**Comment by OverlordZorn** [comment]
So apparently...

for whatever reason, when ace is not laoded, a certain loop of death, caused by [{...},[], 0] call cba_waitandexecute, caused the game to freeze. when ace is loaded, it doesnt happen, thats why it didnt occour during my testing with hemtt launch xyz.

replaced the 0 with 0.1 and it works fine now. ACE has nothing to do with this :harold:

need to validate if the fix really solves it etc but fix should be published soon
